config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :foods, only: %i[index new create destroy]
  resources :recipes, only: %i[index new create show destroy]

  # Defines the root path route ("/")
  root "recipes#index"
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    return unless user.present?

    can :read, :all
    cannot :update, :all
    can :manage, Food, user_id: user.id
    can :manage, Recipe, user_id: user.id
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :user, class_name: 'User', foreign_key: 'user_id', inverse_of: :foods
  has_many :inventory_foods, class_name: 'InventoryFood', foreign_key: 'food_id', inverse_of: :food, dependent: :destroy
  has_many :recipe_foods, class_name: 'RecipeFood', foreign_key: 'food_id', inverse_of: :food, dependent: :destroy

  validates :name, presence: true
  validates :measurement_unit, presence: true
  validates :price, presence: true, numericality: true, comparison: { greater_than: 0 }
end

app/models/inventory.rb
class Inventory < ApplicationRecord
  belongs_to :user, class_name: 'User', foreign_key: 'user_id', inverse_of: :inventories
  has_many :inventory_foods, class_name: 'InventoryFood', foreign_key: 'inventory_id', inverse_of: :inventory,
                             dependent: :destroy
end

app/models/inventory_food.rb
class InventoryFood < ApplicationRecord
  belongs_to :inventory, class_name: 'Inventory', foreign_key: 'inventory_id', inverse_of: :inventory_foods
  belongs_to :food, class_name: 'Food', foreign_key: 'food_id', inverse_of: :inventory_foods
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user, class_name: 'User', foreign_key: 'user_id', inverse_of: :recipes
  has_many :recipe_foods, class_name: 'RecipeFood', foreign_key: 'recipe_id', inverse_of: :recipe, dependent: :destroy

  validates :name, presence: true
  validates :preparation_time, presence: true, numericality: true, comparison: { greater_than: 0 }
  validates :cooking_time, presence: true, numericality: true, comparison: { greater_than: 0 }
  validates :description, presence: true

  after_initialize :default_values

  private

  def default_values
    self.public ||= false
  end
end

app/models/recipe_food.rb
class RecipeFood < ApplicationRecord
  belongs_to :recipe, class_name: 'Recipe', foreign_key: 'recipe_id', inverse_of: :recipe_foods
  belongs_to :food, class_name: 'Food', foreign_key: 'food_id', inverse_of: :recipe_foods
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :confirmable
  has_many :foods, class_name: 'Food', foreign_key: 'user_id', inverse_of: :user, dependent: :destroy
  has_many :recipes, class_name: 'Recipe', foreign_key: 'user_id', inverse_of: :user, dependent: :destroy
  has_many :inventories, class_name: 'Inventory', foreign_key: 'user_id', inverse_of: :user, dependent: :destroy

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :update_allowed_parameters, if: :devise_controller?

  private

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password, :password_confirmation) }
    devise_parameter_sanitizer.permit(:account_update) do |u|
      u.permit(:name, :email, :password, :password_confirmation, :current_password)
    end
  end
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  def index
    @curret_user = current_user
    @f_order = params[:order] || 'asc'
    @foods = Food.all.order("name #{@f_order}")
  end

  def new
    @current_user = current_user
    @food = Food.new(name: params[:name], measurement_unit: params[:meas_unit], price: params[:price])
  end

  def create
    @current_user = current_user
    @food = @current_user.foods.new(food_params)
    if @food.save
      flash[:notice] = 'Food was successfully created.'
      redirect_to foods_url
    else
      flash.now[:alert] = @food.errors.full_messages.to_sentence
      render :new, status: 422
    end
  end

  def destroy
    @current_user = current_user
    @food = Food.find(params[:food][:food_id])
    if @food.destroy
      flash[:notice] = 'Food was successfully removed.'
    else
      flash.now[:alert] = @food.errors.full_messages.to_sentence
    end
    redirect_to foods_path
  end

  private

  def food_params
    params.require(:food).permit(:name, :measurement_unit, :price)
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def index
    @curret_user = current_user
    @recipes = @current_user.recipes.order(created_at: :desc)
  end

  def show
    @current_user = current_user
    @recipe = Recipe.find(params[:id])
    @f_field = params[:field] || 'name'
    @f_order = params[:order] || 'asc'
    @rec_foods = RecipeFood.joins(:food).where(recipe_id: params[:id]).order("#{@f_field} #{@f_order}").includes(:food)
  end

  def new
    @current_user = current_user
    @recipe = Recipe.new(name: params[:name], preparation_time: params[:preparation_time],
                         cooking_time: params[:cooking_time], description: params[:description],
                         public: params[:public])
  end

  def create
    @current_user = current_user
    @recipe = @current_user.recipes.new(recipe_params)
    if @recipe.save
      flash[:notice] = 'Recipe was successfully created.'
      redirect_to foods_url
    else
      flash.now[:alert] = @recipe.errors.full_messages.to_sentence
      render :new, status: 422
    end
  end

  def destroy
    @current_user = current_user
    @recipe = Recipe.find(params[:recipe][:recipe_id])
    if @recipe.destroy
      flash[:notice] = 'Recipe was successfully removed.'
    else
      flash.now[:alert] = @recipe.errors.full_messages.to_sentence
    end
    redirect_to recipes_path
  end

  private

  def recipe_params
    params.require(:recipe).permit(:name, :preparation_time, :cooking_time, :description, :public)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/foods/index.html.erb
<div class="box__buttons">
  <%= link_to 'New Food', new_food_path, class: 'btn' %>
</div>
<div class="box__table">
  <table>
    <thead>
    <tr>
      <th><%= link_to 'FOOD', foods_path(order: (@f_order == 'asc' ? 'desc' : 'asc')) %></th>
      <th>MEASUREMENT UNIT</th>
      <th>PRICE</th>
      <th>ACTIONS</th>
    </tr>
    </thead>
    <tbody>
      <% @foods.each do |food| %>
        <tr>
          <td><%= food.name %></td>
          <td><%= food.measurement_unit %></td>
          <td><%= food.price %></td>
          <td>
            <%= button_to 'Delete', food_path(food.id), params: { food: { food_id: food.id } }, method: :delete, id: "btn__delete-food-#{food.id}" %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/foods/new.html.erb
<div class="form__container">
<%= tag.h1('New Food', class: 'form__title') %>
<%= form_for @food do |f| %>
  <%= f.text_field :name, placeholder: 'Name' %>
  <%= f.text_field :measurement_unit, placeholder: 'Measurement unit' %>
  <%= f.text_field :price, placeholder: 'Price per unit' %>
  <%= f.submit 'Save', class: 'btn' %>
<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RecipeApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/recipes/_recipe_card.html.erb
<div class="card__box">
  <div class="card__box-head">
    <%= tag.h1(recipe.name, class: 'card__title') %>
    <% if can? :destroy, recipe %>
      <%= button_to 'Remove', recipe_path(recipe.id), params: { recipe: { recipe_id: recipe.id} }, method: :delete, class: 'link remove__link-float', id: "btn__delete-recipe-#{recipe.id}" %>
    <% end %>
  </div>
  <div class="card__box-description">
    <%= tag.p(recipe.description, class: ['card__text', ('truncated-text' unless detailed)]) %>
  </div>
  <%= link_to '', recipe_path(recipe.id), id: "link_recipe-#{recipe.id}", class: 'card__hidden-link' %>
</div>

app/views/recipes/index.html.erb
<div class="box__buttons">
  <%= link_to 'New Food', new_food_path, class: 'btn' %>
</div>
<%= render partial: 'recipe_card', collection: @recipes, as: :recipe, locals: { detailed: false } %>

app/views/recipes/new.html.erb
<div class="form__container">
<%= tag.h1('New Recipe', class: 'form__title') %>
<%= form_for @recipe do |f| %>
  <%= f.text_field :name, placeholder: 'Name' %>
  <%= f.text_field :preparation_time, placeholder: 'Preparation time (hours)' %>
  <%= f.text_field :cooking_time, placeholder: 'Cooking time (hours)' %>
  <%= f.text_area :description, rows: 15, placeholder: 'Enter the description' %>
  <div class="field">
    <%= f.label :public %>
    <%= f.check_box :public, {checked: true}, true, false %>
  </div>
  <%= f.submit 'Save', class: 'btn' %>
<% end %>
</div>

app/views/recipes/show.html.erb
<div class="recipe__details">
  <%= tag.h1(@recipe.name) %>
  <div class="recipe__info">
    <div class="recipe__info-item">
      <%= tag.span('Preparation time:') %>
      <%= tag.p("#{@recipe.preparation_time} hours") %>
    </div>
    <div class="recipe__info-item">
      <%= tag.span('Cooking time:') %>
      <%= tag.p("#{@recipe.cooking_time} hours") %>
    </div>
    <div class="recipe__info-item">
      <%= tag.span('Preparation steps:') %>
      <%= @recipe.description %>
    </div>
    <div class="recipe__info-item public__item-float">
      <%= tag.span('Public:') %>
      <label class="toggle__switch">
        <%= check_box_tag 'public_recipe', 'yes', @recipe.public, disabled: true %>
        <span class="slider round"></span>
      </label>
    </div>
  </div>
  <div class="recipe__buttons">
    <% if can? :destroy, @recipe %>
      <%= link_to 'Generate shopping list', '', class: 'btn', id: 'link__shopping-list' %>
      <%= link_to 'Add ingredient', '', class: 'btn', id: 'link__add-ingredient' %>
    <% end %>
  </div>
  <div class="recipe__ingredients">
    <table>
      <thead>
      <tr>
        <th><%= link_to 'Food', recipe_path(@recipe.id, field: 'name', order: (@f_field == 'name' && @f_order == 'asc' ? 'desc' : 'asc')), class: 'link link__table-head' %></th>
        <th><%= link_to 'Quantity', recipe_path(@recipe.id, field: 'quantity', order: (@f_field == 'quantity' && @f_order == 'asc' ? 'desc' : 'asc')), class: 'link link__table-head' %></th>
        <th>Value</th>
        <% if can? :destroy, @recipe %>
        <th>Action</th>
        <% end %>
      </tr>
      </thead>
      <tbody>
        <% @rec_foods.each do |rf| %>
          <tr>
            <td><%= rf.food.name %></td>
            <td><%= rf.quantity %></td>
            <td><%= "$ #{rf.quantity * rf.food.price}" %></td>
            <% if can? :destroy, @recipe %>
            <td class="table__actions">
              <%= link_to 'Modify', '', class: 'link' %>
              <%= button_to 'Remove', '', params: { recipe_food: { rf_id: rf.id }}, method: :delete, class: 'link' %>
            </td>
            <% end %>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>